### ISSUE TITLE
disable not working as expected

### ISSUE THREAD

**Issue by LastxTemplar** [Wayaer/fl_pip#13]
calling `FlPiP().disable();` has the same effect as calling `FlPiP().enable(...);`
When calling `disable` the app minimises and shows the PiP view.

I am not sure what I'm doing wrong, also there is no method calling disable() in the example app.

I would expect that calling `disable()` would disable the app from showing PiP when minimising.

**Comment by Wayaer** [comment]
Try updating to the latest version
