### ISSUE TITLE
使用enableWithEngine和不使用的区别是什么？

### ISSUE THREAD

**Issue by wengxianxun** [Wayaer/fl_pip#17]
使用enableWithEngine和不使用的区别是什么？  如果画中画是播放视频，该不该用？

**Comment by Wayaer** [comment]
重新开启了一个新的FlutterEngin，相当于开启了新的 main方法，运行runapp

**Comment by wengxianxun** [comment]
> 重新开启了一个新的FlutterEngin，相当于开启了新的 main方法，运行runapp

如果画中画是播放视频，该不该用？

**Comment by Wayaer** [comment]
没必要用
