### ISSUE TITLE
进入后台调用enable闪退，帮忙看看是不是我写的有问题

### ISSUE THREAD

**Issue by wengxianxun** [Wayaer/fl_pip#19]
进入后台监听调用代码
@override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.paused) {
      // 应用进入后台
      print('App is in the background');
      await FlPiP()
          .enable(
              ios: const FlPiPiOSConfig(
                  path: 'assets/landscape.mp4', packageName: null),
              android:
                  const FlPiPAndroidConfig(aspectRatio: Rational.landscape()))
          .then((value) {});
    } else if (state == AppLifecycleState.resumed) {
      // 应用返回前台
      print('App is in the foreground');
    }
  }

错误代码
E/flutter (15266): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Activity must be resumed to enter picture-in-picture, null, java.lang.IllegalStateException: Activity must be resumed to enter picture-in-picture
E/flutter (15266): 	at android.app.Activity.enterPictureInPictureMode(Activity.java:2860)
E/flutter (15266): 	at fl.pip.FlPiPActivity$PiPPlugin.enablePiP(FlPiPActivity.kt:211)
E/flutter (15266): 	at fl.pip.FlPiPActivity$PiPPlugin.enable(FlPiPActivity.kt:190)
E/flutter (15266): 	at fl.pip.FlPiPActivity$PiPPlugin.onMethodCall(FlPiPActivity.kt:103)
E/flutter (15266): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (15266): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (15266): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (15266): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (15266): 	at android.os.Handler.handleCallback(Handler.java:900)
E/flutter (15266): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/flutter (15266): 	at android.os.Looper.loop(Looper.java:219)
E/flutter (15266): 	at android.app.ActivityThread.main(ActivityThread.java:8673)
E/flutter (15266): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (15266): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter (15266): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/flutter (15266): )
E/flutter (15266): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (15266): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (15266): <asynchronous suspension>
E/flutter (15266): #2      FlPiP.enable (package:fl_pip/fl_pip.dart:117:19)
E/flutter (15266): <asynchronous suspension>
E/flutter (15266): #3      LifecycleObserver.didChangeAppLifecycleState.<anonymous closure> (package:demo/LifecycleObserver.dart:22:17)
E/flutter (15266): <asynchronous suspension>
E/flutter (15266): #4      LifecycleObserver.didChangeAppLifecycleState (package:demo/LifecycleObserver.dart:16:7)
E/flutter (15266): <asynchronous suspension>
E/flutter (15266): 
I/flutter (15266): _playerController.value.playingState:PlayingState.paused
I/flutter (15266): _listen:0:00:08.901000
D/ZrHung.AppEyeUiProbe(15266): not watching, wait.
Application finished.

**Comment by Wayaer** [comment]
https://github.com/Wayaer/fl_pip/blob/b72e0fa61a6e6fb11095c698ae6c1fa7afd5cc1a/example/lib/main_app.dart#L112
