### ISSUE TITLE
画中画默认大小和位置设置无效

### ISSUE THREAD

**Issue by wengxianxun** [Wayaer/fl_pip#21]
设置rect后，还是默认的位置和大小，这样对吗？
<img width="908" alt="image" src="https://github.com/Wayaer/fl_pip/assets/831898/76344b2d-91f5-41d4-bd85-7fe596bf71c7">

**Comment by wengxianxun** [comment]
![image](https://github.com/Wayaer/fl_pip/assets/831898/138f2dde-ed3b-451c-bb44-e52a044de321)
我的理想是像腾讯这样初始大小，现在的默认界面有点小

**Comment by Wayaer** [comment]
https://github.com/Wayaer/fl_pip/blob/b72e0fa61a6e6fb11095c698ae6c1fa7afd5cc1a/lib/fl_pip.dart#L170

**Comment by Wayaer** [comment]
https://github.com/Wayaer/fl_pip/blob/b72e0fa61a6e6fb11095c698ae6c1fa7afd5cc1a/lib/fl_pip.dart#L237
