### ISSUE TITLE
切换到后台后点击UI按钮调用FlPiP 的所有函数都会提示没有注册

### ISSUE THREAD

**Issue by AsherDubai** [Wayaer/fl_pip#25]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method isActive on channel fl_pip)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      FlPiP.isActive (package:fl_pip/fl_pip.dart:132:17)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      pipMain.<anonymous closure> (package:qiuliao/main.dart:223:24)
                                                                                                    <asynchronous suspension>

目的是想要添加在系统桌面的PIP组件可以关闭PIP功能，目前只有自带的右上角可以点击进入APP

**Comment by Wayaer** [comment]
更新下 3.0.0
