### ISSUE TITLE
fl_pip Example Fails to Compile: “The method ‘CountDown’ isn’t defined for the type ‘Timer’”

### ISSUE THREAD

**Issue by Turskyi** [Wayaer/fl_pip#30]
The example project for the fl_pip package fails to compile due to missing definitions and unused imports in the lib/main.dart file.

Steps to Reproduce:
	1.	Clone the repository:
	```
	git clone https://github.com/Wayaer/fl_pip.git
	```
	2.	Navigate to the example folder:
	```
	cd fl_pip/example
	```
	3.	Open the example project in your IDE (e.g., Android Studio, VS Code).
	4.	Open the lib/main.dart file.
	5.	Attempt to build or run the app.
	6.	Observe the following errors in the IDE or console:
	**Errors:**
	1.	Missing Method:
```
The method 'CountDown' isn't defined for the type 'Timer'.
```
2.	Unused Import:
	```
	Unused import: 'package:flutter_waya/ flutter_waya. dart'.
	```
	Expected Behavior:

The example app should compile and run without errors, demonstrating the functionality of the fl_pip package.

Environment:
	•	Flutter Version:
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] IntelliJ IDEA Community Edition (version 2024.3)
[✓] VS Code (version 1.95.3)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```
•	IDE: Android Studio
	•	Operating System: macOS

**Comment by Wayaer** [comment]
The issue has been fixed, please update the code

**Comment by savan-sangani** [comment]
for iOS getting blank when pip is active is there any solution ?
