### ISSUE TITLE
FlPip().enable的参数rect问题

### ISSUE THREAD

**Issue by PokiFOX** [Wayaer/fl_pip#4]
FlPiP().enable(
  ios: const FlPiPiOSConfig(
    path: 'assets/landscape.mp4',
    packageName: null,
    rect: Rect.fromLTWH(0, 0, 50, 50),
  ),
  android: const FlPiPAndroidConfig(
    aspectRatio: Rational.maxLandscape(),
  ),
);
我采用这个方法调用enable，但是打开的pip大小和传入rect:null的结果是一样的，请问要如何修改pip的大小呢？

**Comment by Wayaer** [comment]
ios中的rect 参数是控制 视频播放的大小 无特殊要求不需要修改。要修改pip形状或者大小，需要使用给path参数传入一个视频地址，视频的宽高比和大小 修改pip大小，同样需要设置packageName 为null,再example有例子
![image](https://github.com/Wayaer/fl_pip/assets/17231965/25c82b8f-1af4-4cf9-9db7-0538f617041e)
![image](https://github.com/Wayaer/fl_pip/assets/17231965/f9229303-3e35-4b02-a458-5f0eec4dc52b)

**Comment by PokiFOX** [comment]
改变mp4的尺寸的确可以达到效果，感谢。我还有一个额外的问题，这个画中画中即使有TextButton等控件应该也是无法响应的吧，那是否有办法将默认视频播放器的Play/Pause传递给listener呢？

**Comment by Wayaer** [comment]
> 改变mp4的尺寸的确可以达到效果，感谢。我还有一个额外的问题，这个画中画中即使有TextButton等控件应该也是无法响应的吧，那是否有办法将默认视频播放器的Play/Pause传递给listener呢？

可以响应手势，后续看下能不能添加listener
