### ISSUE TITLE
iOS - App stops responding

### ISSUE THREAD

**Issue by boradparas** [Wayaer/fl_pip#8]
`@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      FlPiP().enable(
        ios: const FlPiPiOSConfig(
          enabledWhenBackground: true,
          createNewEngine: true,
        ),
      );
      unawaited(videoRoomStore.resumeAllListeners());
    } else {
      videoRoomStore.pauseAllListeners();
    }
  }`
  
  And when I do it on button click it works fine but in every case the video is shown for first 2 seconds and then PIP turns grey (2 problems)

**Comment by Wayaer** [comment]
This seems to be because after the app enters the background, the application is restricted by the ios system, and there is no solution at present, even if the background process is configured in xcode
